user  nginx;
worker_rlimit_nofile 65535;

error_log  stderr notice;
pid        /run/nginx.pid;

events {
    worker_connections  4096;
    multi_accept on;
    use epoll;
}

include /etc/nginx.d/*.conf;
