include /etc/nginx/snippets/tls.conf;

ssl_certificate        /etc/certs/ruconet/cert.pem;
ssl_certificate_key    /etc/certs/ruconet/key.pem;
ssl_client_certificate /etc/certs/ruconet/ca.pem;
ssl_verify_client      on;
ssl_verify_depth       1;
